spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/p2p
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #    initialization-mode: always
  jpa:
    hibernate:
      #      ddl-auto: none
      ddl-auto: create
    #      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace

server:
  error:
    include-stacktrace: never

    # swagger-doc : /doc/swagger-ui.html
  servlet:
    context-path: /doc
